### ISSUE TITLE
Fix String-to-bytes and bytes-toString for UTF-8 for all remaining code

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#4765]
As a follow-on to #3815, which fixed these conversions for all non-test code in the 2.1 branch for 2.1.3, the same should be done for all code in the main/3.1 branch, and should include test code as well (at the very least to set a good example for developers coming along later; we should just have a habit of being rigorous with encoding issues regardless of its location).

**Comment by meatballspaghetti** [comment]
I can look into this.

**Comment by dlmarion** [comment]
@meatballspaghetti - is this issue resolved now?

**Comment by meatballspaghetti** [comment]
@dlmarion Not resolved yet, only 2.1.3 has been taken care of with PR #4791. Next I'll be taking a look at main/3.1 branch for any UTF-8 encoding that needs to be added there, which would still fall in this particular issue.

**Comment by ctubbsii** [comment]
Re-opening in case there's more to do for 4.0/main

**Comment by meatballspaghetti** [comment]
Nothing more to do in main for this issue.

**Comment by ctubbsii** [comment]
Just noting here that the merge of #4847 in df8a3670a4100bee083a02d6ac6f45ff36ffe8f6 did include an additional fix for the main/4.0 branch.
